### ISSUE TITLE
Choice of colors for tags

### ISSUE THREAD

**Issue by Nevarro** [Beaver-Notes/Beaver-Notes#124]
**Is your feature request related to a problem? Please describe.**
Similarly to your blog, it'd be easier to distinguish notes by having the ability to change the individual tag color. 

**Describe the solution you'd like**
Tag color picker, ideally with a field for color codes. 

**Describe alternatives you've considered**

**Additional context**

**Comment by Daniele-rolli** [comment]
It sounds like a cool idea, and as you can see, I've already added it to our roadmap. I'll make sure to implement this feature after the work on the mobile app is done.

**Comment by Daniele-rolli** [comment]
Hey @Nevarro, I'm looking into ways to add a color choice for tags. So far, I've managed to add them to the editor. However, now I'm undecided about whether we should also display the color-coded tags on the home screen. The issue is that the notecards don't distinguish between tags; they simply place everything into a single div. Therefore, we would need to rewrite the note card. What's your take on this?

**Comment by Daniele-rolli** [comment]
This issue will be closed due to a lack of interest and a structural change required to implement this feature, which would jeopardize Beaver Notes' user experience.
