### ISSUE TITLE
Ctrl+P opens print menu instead of the command prompt

### ISSUE THREAD

**Issue by mufeedali** [Beaver-Notes/Beaver-Notes#184]
**Bug Description**
Ctrl+P opens print menu instead of the command prompt

**To Reproduce**
1. Press `Ctrl+P`
2. Opens print menu.

**Expected Behavior**
The command prompt should appear instead.

**Screenshots**
![image](https://github.com/Beaver-Notes/Beaver-Notes/assets/28823274/e8339cff-0882-4499-92f3-684ab57a77f3)
	
**Desktop (please complete the following information):**
- OS: Arch Linux, Flatpak
- Application Version: 3.2.0

**Comment by Daniele-rolli** [comment]
Thanks for reporting this to us! I know keyboard shortcuts can sometimes be confusing, especially if you are new to an app. That's why we created a shortcuts section in settings. Beaver Notes uses Ctrl + P to print a note and Ctrl + Shift + P to open the command prompt. If you need any help or clarification, don't hesitate to ask. Thanks again for opening this issue.

**Comment by mufeedali** [comment]
![image](https://github.com/Beaver-Notes/Beaver-Notes/assets/28823274/8eb68fd6-be54-4cbb-a6e5-12747e80c2d3)

You might want to update your tutorial then :)

**Comment by Daniele-rolli** [comment]
Noted! I'll make sure it gets updated.
