### ISSUE TITLE
Scrollbar doesn't switch to dark colors on dark mode

### ISSUE THREAD

**Issue by senntore** [Beaver-Notes/Beaver-Notes#185]
**Bug Description**
In Dark mode, the scrollbar doesn't switch dark colors. It looks out of place & inconsistent with app's UI.

**To Reproduce**
1. Go to Settings
2. Switch to Appearance page.
3. Observe the error.

**Expected Behavior**
The scrollbar should switch to dark colors in dark mode.

**Screenshots**
![image](https://github.com/Beaver-Notes/Beaver-Notes/assets/58325574/aba3426f-56a5-4a3c-8a38-7228d0b5dab0)

**Desktop (please complete the following information):**
- OS: Pop!_OS 22.04
- Application Version: 3.2.0

**Additional Context**
I believe this issue is because of the default chrome scrollbars in the electron but I've seen other applications like Obsidian & Logseq which has custom scrollbars that respect the dark mode & the theme.

**Comment by Daniele-rolli** [comment]
Thanks for your feedback! As you correctly pointed out, the issue lies in how Electron handles scrollbars. That being said, @bigshans has already taken care of this design flaw. Thanks again for helping us make Beaver better.

<img width="1131" alt="Screenshot 2024-05-20 at 8 38 59 AM" src="https://github.com/Beaver-Notes/Beaver-Notes/assets/67503004/e7b3aba7-557d-44b1-837a-89dba4a2f03f">
<img width="1131" alt="Screenshot 2024-05-20 at 8 39 02 AM" src="https://github.com/Beaver-Notes/Beaver-Notes/assets/67503004/ad016dcd-7ae6-49eb-87a8-731f311e64da">
