### ISSUE TITLE
Feature request: Folder tree

### ISSUE THREAD

**Issue by reblex** [Beaver-Notes/Beaver-Notes#211]
**Is your feature request related to a problem? Please describe.**
Difficulty organizing notes.

**Describe the solution you'd like**
This app is amazing, but what I'm missing is organization. I would use this app if there was a simple tree structure with collapsable folders, similar to Obsidian or VS Code, where you can see folders and their files in a nested structure.

**Describe alternatives you've considered**
I personally do not like list or gallery views, because I think it gets a bit crowded when you have many files. I prefer a collapsible folder tree, as described above.

**Additional context**
No.

**Comment by vorwd** [comment]
I agree, this could be very useful, especially when our notes grow to hundreds overtime... without it, I am having to make the decision to use a single note that will span hundreds of days of notes, which is not ideal... preferred method would be to have a folder for a month, then notes on a day level.

**Comment by Daniele-rolli** [comment]
Thanks for the input, folks! Beaver's design philosophy is to simplify and improve note-taking, which is why we've chosen to replace folders with labels and the tree structure with a card view. Personally, I use two labels one for the year and the other for the  month for each of my notes to categorize them. Additionally, I use the archive feature to hide notes that I don't want in my way but might still need later. I know this might be a big adjustment coming from more standard note taking apps however I hope this reply helps you better organize your notes.

**Comment by vorwd** [comment]
Understandable -- and yes, a big change, but I am open to giving it a go.  Thanks for the advice.
