### ISSUE TITLE
Unable to install from scoop

### ISSUE THREAD

**Issue by grand-lotus-iroh** [Beaver-Notes/Beaver-Notes#215]
I visit https://beavernotes.com/#/Packages and click Scoop than on step #2 I get error:

![image](https://github.com/user-attachments/assets/640b2d70-3cc9-421d-8045-feb29829ba7c)

**Comment by grand-lotus-iroh** [comment]
also just noticed, for some reason it's not on website, https://scoop.sh/#/apps?q=beaver+notes

maybe find a way to get this posted on there if you wanted

**Comment by Daniele-rolli** [comment]
Thanks for the feedback! I've changed the hashes for both files and performed a health check on my Windows 11 installation, and everything seems to work fine now. I also plan to implement automatic health checks for the Scoop repo to ensure this won't happen again. About availability on scoop.sh, we are not in the official repos. However, if you disable the 'official repos only' filter, you should see us there. We decided to have our own repo instead of using the official one for the sake of efficiency as it allows us to solve issues like this quickly.
