### ISSUE TITLE
Link feature doesn't work 

### ISSUE THREAD

**Issue by guguss-31** [Beaver-Notes/Beaver-Notes#258]
**Bug Description**
When i want to convert text to link with Beaver Note 🤩, i get a link formatting but when i press ctrl+click , it doesn't open the link 😭. 

**To Reproduce**
1. Create a note 
2. Write into it ✍️
3. Select link 
4. Click on the link button in the options
5. Press ctrl+click 
6. It doesn't work 😕

**Screenshots**
![image](https://github.com/user-attachments/assets/ff9db607-458a-4209-a914-81fa549c92b3)

**Desktop (please complete the following information):**
- OS: Windows 11 Professionnel Éducation v24H2
- Application Version: 3.7.0

**Comment by Daniele-rolli** [comment]
Thanks for reporting this issue. Please try using Alt + click instead of Ctrl + click. We had to change the shortcut due to the introduction of context menus. However, the translations were never updated. We are aware of the issue and plan to address it in the next release. Unfortunately, we're currently tied up with the mobile app, which is why the issue hasn't been resolved yet.

**Comment by guguss-31** [comment]
Thank you very much !!!!!🤩👍😀
